# Generated by Django 4.1.5 on 2023-02-20 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="myuser",
            name="period",
            field=models.FloatField(default=float),
        ),
    ]
