# Generated by Django 4.1.5 on 2023-02-22 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_myuser_period"),
    ]

    operations = [
        migrations.AddField(
            model_name="myuser",
            name="last_post",
            field=models.FloatField(default=float),
        ),
    ]
